### ISSUE TITLE
头像路径

### ISSUE THREAD

**Issue by jiaobendaye** [xiaoluoboding/ghost-theme-kaldorei#49]
想要使用自己定义的头像，怎么设置呢？在哪里修改路径？

**Comment by xiaoluoboding** [comment]
不用修改路径，Ghost后台直接上传即可         
            
                
                    
                            
                                
                            
                            
                                xiaoluoboding
                            
                    
                        
                            
                                    邮箱：xiaoluoboding@gmail.com
                            
                        
                
            
        在2020年12月07日 11:49，jiaobendaye 写道： 

想要使用自己定义的头像，怎么设置呢？在哪里修改路径？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/xiaoluoboding/ghost-theme-kaldorei/issues/49",

"url": "https://github.com/xiaoluoboding/ghost-theme-kaldorei/issues/49",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jiaobendaye** [comment]
好的，谢谢！
